### ISSUE TITLE
API Rate Limiting

### ISSUE THREAD

**Issue by chrisgithub1985** [obrigg/meraki-health-check#3]
Is it possible to throttle requests so that it doesnt hit the rate limit by the Meraki API? Keep getting 429 errors when running.

**Comment by obrigg** [comment]
Certainly. On line 1229 you can adjust the number of calls per second the script will try to use. 
It’s currently set on 5, and the rate limit is 10. That means you have other applications consuming API budget. 
You can decrease the number or increase the back off timeout, allowing the script to run.

**Comment by chrisgithub1985** [comment]
Legend. Thank you!
