### ISSUE TITLE
meraki-health-check-master\async_run.py", line 1386

### ISSUE THREAD

**Issue by tompane** [obrigg/meraki-health-check#7]
Fetching ethernet ports, received 0 ethernet ports so far..
Traceback (most recent call last):
  File "C:\meraki-health-check-master\async_run.py", line 1386, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\meraki-health-check-master\async_run.py", line 1339, in main
    check_wireless_ports(networks)
  File "C:\meraki-health-check-master\async_run.py", line 745, in check_wireless_ports
    if ap["serial"] in results[network_name]["channel_utilization_check"].keys():
                       ~~~~~~~^^^^^^^^^^^^^^
KeyError: 'N/A'

**Comment by obrigg** [comment]
Interesting. Thanks for reporting this.
Do you have a network with no name under this organization?

**Comment by tompane** [comment]
No not in this targeted organization.
 

![2023-08-30_13-19-33](https://github.com/obrigg/meraki-health-check/assets/22482947/05f1057d-72cd-46d1-8577-07504f6dfe77)

**Comment by obrigg** [comment]
Weird.. the value "N/A" suggests the network ID was not translated into the network's name.
```
    for ap in aggregated_ap_uplinks:
        # Translating network ID to network name
        network_id = ap['network']['id']
        network_name = "N/A"
        for network in networks:
            if network['id'] == network_id:
                network_name = network['name']
                break
```

Can you kindly print or pause at debug the value of `networks` and verify all networks have a name?

**Comment by obrigg** [comment]
Thanks to JPYDX (https://github.com/obrigg/meraki-health-check/issues/8), we may have a lead on this.
Can you kindly add a print statement for the AP?

```
    for ap in aggregated_ap_uplinks:
        print(ap)
        # Translating network ID to network name
        network_id = ap['network']['id']
        network_name = "N/A"
        for network in networks:
            if network['id'] == network_id:
                network_name = network['name']
                break
```

I'd like to see which AP cause the script to break, and whether there's a problem with it's Network ID.

**Comment by tompane** [comment]
It worked and ran to completion.
{'serial': 'Q2KD-5VN4-FSxx', 'name': 'NYC 12th WLAN AP 5', 'network': {'id': 'L_647955396387930853'}, 'power': {'mode': 'full', 'ac': {'isConnected': False}, 'poe': {'isConnected': True}}, 'ports': [{'name': 'Ethernet 0', 'poe': {'standard': '802.3at'}, 'linkNegotiation': {'duplex': 'full', 'speed': 1000}}], 'aggregation': {'enabled': False, 'speed': 1000}}
{'serial': 'Q2KD-8NWS-Xxxx', 'name': 'NYC 12th WLAN AP 4', 'network': {'id': 'L_647955396387930853'}, 'power': {'mode': 'full', 'ac': {'isConnected': False}, 'poe': {'isConnected': True}}, 'ports': [{'name': 'Ethernet 0', 'poe': {'standard': '802.3at'}, 'linkNegotiation': {'duplex': 'full', 'speed': 1000}}], 'aggregation': {'enabled': False, 'speed': 1000}}
{'serial': 'Q2KD-9BPM-ELxx', 'name': 'NYC 12th WLAN AP 6', 'network': {'id': 'L_647955396387930853'}, 'power': {'mode': 'full', 'ac': {'isConnected': False}, 'poe': {'isConnected': True}}, 'ports': [{'name': 'Ethernet 0', 'poe': {'standard': '802.3at'}, 'linkNegotiation': {'duplex': 'full', 'speed': 1000}}], 'aggregation': {'enabled': False, 'speed': 1000}}
{'serial': 'Q2KD-DZK5-ANxx', 'name': 'NYC 12th WLAN AP 3', 'network': {'id': 'L_647955396387930853'}, 'power': {'mode': 'full', 'ac': {'isConnected': False}, 'poe': {'isConnected': True}}, 'ports': [{'name': 'Ethernet 0', 'poe': {'standard': '802.3at'}, 'linkNegotiation': {'duplex': 'full', 'speed': 1000}}], 'aggregation': {'enabled': False, 'speed': 1000}}
{'serial': 'Q2KD-FFDS-64xx', 'name': 'NYC 12th WLAN AP 1', 'network': {'id': 'L_647955396387930853'}, 'power': {'mode': 'full', 'ac': {'isConnected': False}, 'poe': {'isConnected': True}}, 'ports': [{'name': 'Ethernet 0', 'poe': {'standard': '802.3at'}, 'linkNegotiation': {'duplex': 'full', 'speed': 1000}}], 'aggregation': {'enabled': False, 'speed': 1000}}
{'serial': 'Q2KD-GHKX-E3xx', 'name': 'NYC 12th WLAN AP 7', 'network': {'id': 'L_647955396387930853'}, 'power': {'mode': 'full', 'ac': {'isConnected': False}, 'poe': {'isConnected': True}}, 'ports': [{'name': 'Ethernet 0', 'poe': {'standard': '802.3at'}, 'linkNegotiation': {'duplex': 'full', 'speed': 1000}}], 'aggregation': {'enabled': False, 'speed': 1000}}
{'serial': 'Q2KD-NKGL-54xx', 'name': 'NYC 8 th WLAN AP 1', 'network': {'id': 'L_647955396387930853'}, 'power': {'mode': 'full', 'ac': {'isConnected': False}, 'poe': {'isConnected': True}}, 'ports': [{'name': 'Ethernet 0', 'poe': {'standard': '802.3at'}, 'linkNegotiation': {'duplex': 'full', 'speed': 1000}}], 'aggregation': {'enabled': False, 'speed': 1000}}
{'serial': 'Q2KD-QEG2-7Lxx', 'name': 'NYC 12th WLAN AP 8', 'network': {'id': 'L_647955396387930853'}, 'power': {'mode': 'full', 'ac': {'isConnected': False}, 'poe': {'isConnected': True}}, 'ports': [{'name': 'Ethernet 0', 'poe': {'standard': '802.3at'}, 'linkNegotiation': {'duplex': 'full', 'speed': 1000}}], 'aggregation': {'enabled': False, 'speed': 1000}}
{'serial': 'Q2PD-8R52-TYxx', 'name': 'NYC 8 th WLAN AP 3', 'network': {'id': 'L_647955396387930853'}, 'power': {'mode': 'full', 'ac': {'isConnected': False}, 'poe': {'isConnected': True}}, 'ports': [{'name': 'Ethernet 0', 'poe': {'standard': '802.3af'}, 'linkNegotiation': {'duplex': 'full', 'speed': 1000}}], 'aggregation': {'enabled': False, 'speed': 1000}}
{'serial': 'Q2PD-EUP2-XKxx', 'name': 'NYC 8 th WLAN AP 2', 'network': {'id': 'L_647955396387930853'}, 'power': {'mode': 'full', 'ac': {'isConnected': False}, 'poe': {'isConnected': True}}, 'ports': [{'name': 'Ethernet 0', 'poe': {'standard': '802.3af'}, 'linkNegotiation': {'duplex': 'full', 'speed': 1000}}], 'aggregation': {'enabled': False, 'speed': 1000}}
{'serial': 'Q2PD-TV5H-WRxx', 'name': 'NYC 12th WLAN AP 2', 'network': {'id': 'L_647955396387930853'}, 'power': {'mode': 'full', 'ac': {'isConnected': False}, 'poe': {'isConnected': True}}, 'ports': [{'name': 'Ethernet 0', 'poe': {'standard': '802.3af'}, 'linkNegotiation': {'duplex': 'full', 'speed': 1000}}], 'aggregation': {'enabled': False, 'speed': 1000}}
{'serial': 'Q2PD-U7BD-NSxx', 'name': 'NYC 8 th WLAN AP 4', 'network': {'id': 'L_647955396387930853'}, 'power': {'mode': 'full', 'ac': {'isConnected': False}, 'poe': {'isConnected': True}}, 'ports': [{'name': 'Ethernet 0', 'poe': {'standard': '802.3af'}, 'linkNegotiation': {'duplex': 'full', 'speed': 1000}}], 'aggregation': {'enabled': False, 'speed': 1000}}
{'serial': 'Q2PD-UTBC-3Sxx', 'name': 'NYC 8 th WLAN AP 5', 'network': {'id': 'L_647955396387930853'}, 'power': {'mode': 'full', 'ac': {'isConnected': False}, 'poe': {'isConnected': True}}, 'ports': [{'name': 'Ethernet 0', 'poe': {'standard': '802.3af'}, 'linkNegotiation': {'duplex': 'full', 'speed': 1000}}], 'aggregation': {'enabled': False, 'speed': 1000}}

New Error:
Some other ERROR: cannot access local variable 'message_is_dict' where it is not associated with a value

**Comment by obrigg** [comment]
That's interesting, considering the fact I didn't change anything :-)

At what point did you get the new error?
Can you kindly share the few output lines previous to the error?

**Comment by tompane** [comment]
No port errors on switch     NYC 8th Access Switch 1-7
No port errors on switch NYC 12th External - PilotFiber
No port errors on switch NYC 12th External - RCN
No port errors on switch     NYC 12th Access Switch 2-1
STP is enabled for network NewYorkCity
STP is enabled for network ParisOffice
Jumbo Frames enabled for network NewYorkCity (MTU: 9578)
Jumbo Frames enabled for network ParisOffice (MTU: 9578)
Some other ERROR: cannot access local variable 'message_is_dict' where it is not associated with a value
Storm-control is not supported for network ParisOffice.
Storm-control is disabled for network NewYorkCity. Best practices suggest a limit should be configured.
5GHz Channel did not exceed 20% for AP Q2KD-5VN4-FSMM, max utilization was 15.53
5GHz Channel Utilization exceeded 20% 1 times, with a peak of 22.24% for AP Q2KD-8NWS-XSZK
5GHz Channel Utilization exceeded 20% 1 times, with a peak of 24.27% for AP Q2KD-9BPM-ELRW
5GHz Channel Utilization exceeded 20% 1 times, with a peak of 38.58% for AP Q2KD-DZK5-ANYC
5GHz Channel Utilization exceeded 20% 27 times, with a peak of 44.63% for AP Q2KD-FFDS-647R
5GHz Channel Utilization exceeded 20% 3 times, with a peak of 22.26% for AP Q2KD-GHKX-E3JM

**Comment by obrigg** [comment]
Hmmm... between the MTU/Jumbo frame check and the storm-control check, there are no other checks.
I am not sure where is this error coming from, especially as I don't have a local variable called `message_is_dict`.

Was the script able to run to completion and generate an excel file?

**Comment by tompane** [comment]
Yes, it ran to completion and generated a spreadsheet.

**Comment by obrigg** [comment]
I'm glad to hear. Not sure where that message came from.
Would you like to try and dive deeper into it, or close the issue?

**Comment by tompane** [comment]
Let's close it.

**Comment by obrigg** [comment]
Thanks. I hope the report is helpful!
